version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.8-management 
    ports:
      - 5672:5672
      - 15672:15672
    container_name: rabbitmq
    restart: unless-stopped
    # Default username/password is guest/guest